SPM-LMS-T6/project-SBRPg8t6

server/server.py

Testing of Github Actions CI/CD Pipeline

A2SG-20-Setup-Github-Actions

---

data/init.sql
docker-compose.yml

Added database schema v1 based on the technical considerations

A2SG-30-Create-Database-Schema

---

client/package-lock.json
client/package.json

A2SG-34-SetUu-Sass

---

data/init.sql

Added the seed data with for all tables

A2SG-33-Populate-Seed-Data

---

docker-compose.yml
server/database.py
server/main.py

feat: add rolelisting endpoint
http://localhost:5101/api/v1/rolelistings/

A2SG-21-Create-GET-API-endpoint-to-return-open-roles

---

client/src/components/RoleApplication.vue
client/src/components/RoleDetails.vue
client/src/components/__tests__/RoleDetails.spec.js
client/src/views/JobRoleListView.vue

A2SG-56-link-role-details-to-role-application

---

client/assets/style/style.scss
client/src/components/CalculateRoleMatch.vue
client/src/components/RoleDetails.vue
client/src/router/index.js
client/src/service/UpdateRoleListing.service.js
client/src/service/__tests__/updateRoleListing.spec.js
client/src/views/JobRoleListView.vue
client/src/views/UpdateRoleListingView.vue
client/src/views/__test__/UpdateRoleListingView.spec.js
client/vite.config.js

A2SG-57-link-role-details-to-update-role-view

---

client/src/components/CalculateRoleMatch.vue
client/src/components/RoleDetails.vue
client/src/views/JobRoleListView.vue

display role match percentage in role details component

A2SG-52-Display-Role-Skill-Percentage-on-Component

---

client/src/components/RoleDetails.vue

color code based on matched skills

A2SG-53-Color-code-skills-based-on-skills-matched

---

client/src/views/__test__/UpdateRoleListingView.spec.js

A2SG-81-Check-the-standard-items-in-the-role-modification-feature

---

client/src/views/__test__/UpdateRoleListingView.spec.js

A2SG-84-Visualize-the-workflow-for-modifying-the-details-of-open-roles

---

client/src/views/__test__/UpdateRoleListingView.spec.js

A2SG-82-Verify-how-the-system-handles-a-negative-scenario-when-the-executive-attempts-to-modify-an-open-role-with-invalid-data

---

client/src/views/UpdateRoleListingView.vue
client/src/views/__test__/UpdateRoleListingView.spec.js

A2SG-83-Verify-the-system-s-behavior-when-Open-Date-Description-and-Deadline-Date-fields-are-updated-with-values-at-the-boundary-of-acceptable-ranges

---

client/assets/style/style.css
client/assets/style/style.scss
client/src/views/LoginView.vue
client/src/views/__test__/LoginView.spec.js

Create login UI and test Cases

A2SG-96-Create-Login-Page

---

server/main.py
server/routes/roleListings.py
server/routes/staffdetail.py
server/seed.py

create api to retrieve staff details

A2SG-111-Create-API-to-get-staff-details

---

client/src/views/__test__/JobRoleListView.spec.js

A2SG-114-Displays-No-job-roles-available.-when-no-roles-are-present-HR_Admin-userType

---

client/src/App.vue
client/src/components/CalculateRoleMatch.vue
client/src/components/NavBar.vue
client/src/components/RoleApplication.vue
client/src/components/RoleApplicationTable.vue
client/src/components/RoleDetails.vue
client/src/components/__tests__/NavBar.spec.js
client/src/components/__tests__/RoleApplicationTable.spec.js
client/src/components/__tests__/RoleDetails.spec.js
client/src/router/index.js
client/src/service/__tests__/staffDetails.spec.js
client/src/service/staffDetails.service.js
client/src/views/ApplicationStatusView.vue
client/src/views/CreateRoleListingView.vue
client/src/views/JobRoleListView.vue
client/src/views/LoginView.vue
client/src/views/UpdateRoleListingView.vue
client/src/views/__test__/ApplicationStatusView.spec.js
client/src/views/__test__/CreateRoleListingView.spec.js
client/src/views/__test__/JobRoleListView.spec.js
client/src/views/__test__/LoginView.spec.js
client/src/views/__test__/UpdateRoleListingView.spec.js
server/models.py
server/routes/roleListings.py
server/routes/staffdetail.py
server/seed.py

A2SG-97-Edit-staff-props-for-components-and-logic

---

client/src/components/RoleDetails.vue
client/src/components/__tests__/RoleDetails.spec.js

Verify the workflow of viewing detailed information for open roles. (staff)

A2SG-120-Verify-the-workflow-of-viewing-detailed-information-for-open-roles

---

client/src/components/__tests__/RoleDetails.spec.js

Verify the workflow of viewing detailed information for open roles (hr)

A2SG-121-Verify-the-workflow-of-viewing-detailed-information-for-open-roles.-hr

---

client/src/components/__tests__/RoleDetails.spec.js

Verify the successful display of more skills when selected role have more than two skills

A2SG-122-Verify-the-successful-diplay-of-more-skills-when-selected-role-have-more-than-two-skills

---

client/src/components/__tests__/RoleDetails.spec.js

Check how the system handles the scenario when role does not have certain information

A2SG-123-Check-how-the-system-handles-the-scenario-when-role-does-not-have-certain-information

---

client/src/components/RoleDetails.vue
client/src/components/__tests__/RoleDetails.spec.js
server/seed.py

Check how the system handles the scenario when user has already applied for the role

A2SG-124-Check-how-the-system-handles-the-scenario-when-user-has-already-applied-for-the-role

---

client/src/components/__tests__/RoleDetails.spec.js

A2SG-127-Verifies-how-the-system-handles-viewing-details-of-a-role-with-exceptionally-long-descriptions

---

client/src/components/__tests__/RoleDetails.spec.js

Verifies how the system handles viewing details of a role with more than two skills

A2SG-128-Verifies-how-the-system-handles-viewing-details-of-a-role-with-more-than-two-skills

---

client/src/components/__tests__/RoleDetails.spec.js

Verifies how the system handles viewing details of a role with two skills or less

A2SG-129-Verifies-how-the-system-handles-viewing-details-of-a-role-with-two-skills-or-less

---

client/src/components/CalculateRoleMatch.vue
client/src/views/JobRoleListView.vue
client/src/views/__test__/JobRoleListView.spec.js
server/routes/roleApplicants.py
server/seed.py

Ensure the skill percentage is displayed when a staff member logs in and visits the role listing page

A2SG-139-Ensure-the-skill-percentage-is-displayed-when-a-staff-member-logs-in-and-visits-the-role-listing-page

---

client/src/views/__test__/JobRoleListView.spec.js

Verifies how the system handles role skill matching when there is no matching skills role listing page

A2SG-136-Verifies-how-the-system-handles-role-skill-matching-when-there-is-no-matching-skills-role-listing-page

---

client/src/views/__test__/JobRoleListView.spec.js

Verifies how the system handles role skill matching when user have all skills required for role in role listing page

A2SG-140-Verifies-how-the-system-handles-role-skill-matching-when-user-have-all-skills-required-for-role-in-role-listing-page

---

client/assets/style/style.css
client/assets/style/style.scss
client/src/views/CreateRoleListingView.vue
client/src/views/LoginView.vue

A2SG-146 style: create role listing style

---

client/assets/style/style.css
client/assets/style/style.scss
client/src/components/RoleApplicationTable.vue
client/src/views/UpdateRoleListingView.vue

A2SG-147 style: Role Application Style

---

client/assets/style/_variable.scss
client/assets/style/style.css
client/assets/style/style.scss
client/src/components/RoleApplicationTable.vue
client/src/main.js
client/src/views/RoleApplicantView.vue

A2SG-148 style: Role Applicant style
